name: WebApi Build and Push Docker Image

on:
  workflow_dispatch:  # Allow manual trigger with inputs
    inputs:
      branch:
        description: 'Branch to build from'
        required: true
        default: 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4.2.0
        with:
          ref: ${{ github.event.inputs.branch }} # Use the selected branch

      # Đọc phiên bản từ file .csproj của API
      - name: Get version from API .csproj
        id: get_version_api
        run: |
          csprojContent=$(cat src/Haihv.Elis.Tool.TraCuuGcn.Api/Haihv.Elis.Tool.TraCuuGcn.Api.csproj)
          version=$(echo "$csprojContent" | grep -oP '(?<=<AssemblyVersion>)(.*?)(?=</AssemblyVersion>)')
          echo "VERSION_TAG=$version" >> $GITHUB_ENV
        shell: bash

      - name: Set image name
        run: echo "IMAGE_NAME=haitnmt/tracuugcn-api" >> $GITHUB_ENV

      - name: Check if Docker tag exists
        id: check_tag
        run: |
          if [[ $(docker manifest inspect ${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }} 2>/dev/null) ]]; then
            echo "Tag already exists. Skipping build."
            echo "BUILD=false" >> $GITHUB_ENV
          else
            echo "Tag does not exist. Proceeding with build."
            echo "BUILD=true" >> $GITHUB_ENV
          fi

      - name: Set up .NET SDK
        if: env.BUILD == 'true'
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: '9.x' # Latest .NET version

      - name: Set up docker buildx
        if: env.BUILD == 'true'
        uses: docker/setup-buildx-action@v3.6.0

      - name: Login to docker hub
        if: env.BUILD == 'true'
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        if: env.BUILD == 'true'
        uses: docker/build-push-action@v6.1.0
        with:
          context: ./src
          file: ./src/DockerfileApi  # Đường dẫn tới DockerFile
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.VERSION_TAG }}, ${{ env.IMAGE_NAME }}:latest

      - name: Logout of Docker Hub
        if: env.BUILD == 'true'
        run: docker logout
