name: Build and Deploy KeyCloak Theme

on:
  workflow_dispatch:  # Thêm trigger này để cho phép chạy thủ công
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.0
      
      - name: Login to docker hub
        if: env.BUILD == 'true'
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
      - name: Set image name
        run: echo "IMAGE_NAME=keycloak" >> $GITHUB_ENV
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.1.0
        with:
          context: ./src
          file: ./src/DockerfileKeyCloak
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Logout of Docker Hub
        if: env.BUILD == 'true'
        run: docker logout
