name: ApiSde Build and Push Docker Image

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4.2.0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'  # Latest stable Go version
          cache: true

      # Get version from go.mod or version file
      - name: Get API SDE version
        id: get_version_api_sde
        run: |
          # Assuming version is stored in a VERSION file - adjust as needed
          if [ -f "src/Haihv.Elis.Tool.TraCuuGcn.Api.Sde/version.txt" ]; then
            # Use tr to remove any non-printable characters
            version=$(cat src/Haihv.Elis.Tool.TraCuuGcn.Api.Sde/version.txt | tr -d '\r\n\t\f\v\0\ufeff')
          else
            # Default to a timestamp-based version if no version file exists
            version=$(date +'%Y.%m.%d')
          fi
          echo "API_SDE_VERSION_TAG=$version" >> $GITHUB_ENV
        shell: bash

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3.6.0

      - name: Login to docker hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6.1.0
        with:
          context: ./src
          file: ./src/DockerfileApiSde  # Đường dẫn tới DockerFile
          push: true
          tags: haitnmt/tracuugcn-api-sde:${{ env.API_SDE_VERSION_TAG }}, haitnmt/tracuugcn-api-sde:latest

      - name: Logout of Docker Hub
        run: docker logout