name: Build and Deploy KeyCloak Theme

on:
  workflow_dispatch:  # Thêm trigger này để cho phép chạy thủ công
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.0
      
      - name: Login to docker hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
             
      - name: Build and push Docker image
        uses: docker/build-push-action@v6.1.0
        with:
          context: ./src
          file: ./src/DockerfileKeyCloak  # Đường dẫn tới DockerFile
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/keycloak:latest

      - name: Logout of Docker Hub
        run: docker logout
